#ifndef TL_CONFIG_H
#define TL_CONFIG_H

#include "TL_Device_ID.h"

#define PLATFORM 3
#define BOARD 1005

#define TINYLINK_SERIAL BBB_SERIAL
#define TINYLINK_TIME BBB_TIME
#define TINYLINK_TIMER BBB_TIMER

#define TINYLINK_LED BBB_LED

#define TINYLINK_HUMIDITY DHT11
#define HUMIDITY_DIGITAL_OUTPUT P9_17
#define HUMIDITY_DIGITAL_INPUT P9_18

#define TINYLINK_TEMPERATURE DHT11
#define TEMPERATURE_DIGITAL_OUTPUT P9_17
#define TEMPERATURE_DIGITAL_INPUT P9_18

#define TINYLINK_TEMPERATURE GROVE_TEMPERATURE
#define TEMPERATURE_ANALOG P9_39


#define TINYLINK_SOIL_HUMIDITY SOIL_MOISTURE_ANALOG
#define SOIL_HUMIDITY_ANALOG P9_39

#define TINYLINK_SOIL_HUMIDITY GROVE_MOISTURE
#define SOIL_HUMIDITY_ANALOG P9_39

#define TINYLINK_PM25 SDS018
#define PM25_UART_RX P9_21
#define PM25_UART_TX P9_22

#define TINYLINK_LIGHT GROVE_LIGHT
#define LIGHT_ANALOG P9_40

#define TINYLINK_WIFI WIFI_USB
#define TINYLINK_MQTT BBB_MQTT
#define TINYLINK_hTTP BBB_HTTP

#define TINYLINK_RELAY GROVE_RELAY
#define RELAY_DIGITAL_OUTPUT P9_22
#define RELAY_DIGITAL_INPUT P9_21

#define TINYLINK_BULB GROVE_CHAINABLE_RGB_BULB
#define BULB_DIGITAL_OUTPUT P9_22
#define BULB_DIGITAL_INPUT P9_21

#define TINYLINK_HCHO GROVE_HCHO
#define HCHO_ANALOG P9_37

// DC_Motor by csp
#define TINYLINK_MOTOR GROVE_DC_MOTOR
#define MOTOR_DIGITAL_OUTPUT P9_18
/*

#define TINYLINK_LED OUTLED
#define LED_DIGITAL_OUTPUT P8_12

#define TINYLINK_PM25 SDS018
#define PM25_UART_TX P9_11
#define PM25_UART_RX P9_13

#define TINYLINK_PM10 SDS018
#define PM10_UART_TX P9_11
#define PM10_UART_RX P9_13

#define TINYLINK_GPS U_BLOX
#define GPS_UART_TX P9_22
#define GPS_UART_RX P9_21


#define TINYLINK_STORAGE BBB_SD

#define TINYLINK_SOUND GROVE_SOUND
#define SOUND_ANALOG P9_37
*/


#endif
