#ifndef TL_CONFIG_H
#define TL_CONFIG_H

#include "TL_Device_ID.h"

#define PLATFORM 4
#define BOARD 1003

#define TINYLINK_SERIAL RPI_SERIAL
#define TINYLINK_TIME RPI_TIME
#define TINYLINK_TIMER RPI_TIMER

#define TINYLINK_LED GROVE_LED
#define LED_DIGITAL_INPUT 8
#define LED_DIGITAL_OUTPUT 7

#define TINYLINK_LIGHT GROVE_LIGHT
#define LIGHT_ANALOG A0

#define TINYLINK_TEMPERATURE DHT11
#define TEMPERATURE_DIGITAL_INPUT 5
#define TEMPERATURE_DIGITAL_OUTPUT 4

#define TINYLINK_HUMIDITY DHT11
#define HUMIDITY_DIGITAL_INPUT 5
#define HUMIDITY_DIGITAL_OUTPUT 4

#define TINYLINK_STORAGE RPI_SD

#define TINYLINK_SOIL_HUMIDITY SOIL_MOISTURE_ANALOG
#define SOIL_HUMIDITY_ANALOG A2

#define TINYLINK_GPS U_BLOX
#define GPS_UART_RX 10
#define GPS_UART_TX 8


#define TINYLINK_PM25 SDS018
#define PM25_UART_RX 10
#define PM25_UART_TX 8

#define TINYLINK_WIFI WIFI_USB
#define TINYLINK_HTTP RPI_HTTP
#define TINYLINK_MQTT RPI_MQTT

#define TINYLINK_RELAY GROVE_RELAY
#define RELAY_DIGITAL_INPUT 4
#define RELAY_DIGITAL_OUTPUT 3

#define TINYLINK_VOICE VOICE_USB

#define TINYLINK_DISPLAY GROVE_LCD_RGB

#define TINYLINK_BULB GROVE_CHAINABLE_RGB_BULB
#define BULB_DIGITAL_INPUT 4
#define BULB_DIGITAL_OUTPUT 3

#endif
