#ifndef TL_CONFIG_H
#define TL_CONFIG_H
#include "TL_Device_ID.h"
#define PLATFORM 5
#define BOARD 1011

#define TINYLINK_LED MBED_LED
#define TINYLINK_TIME MBED_TIME
#define TINYLINK_BLUETOOTH MBED_BLUETOOTH
#define TINYLINK_GYRO MBED_GYRO
#define TINYLINK_ACCELEROMETER MBED_ACCELEROMETER

#endif
